version: "3"

services:
  app:
    tty: true
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: yarn start
    build:
      context: ./node-app
    networks:
      - node-net
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
    networks:
      - node-net

  db:
    image: mysql:8
    # command not recommended for production
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    tty: true
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - node-net

networks:
  node-net:
    driver: bridge
